################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
pybindgen/tests \
pybindgen/tests/c-hello \
pybindgen/tests/boost \
pybindgen/examples/h \
pybindgen/examples/g \
pybindgen/examples/f \
pybindgen/examples/e \
pybindgen/examples/d \
pybindgen/examples/callback \
pybindgen/examples/c \
pybindgen/examples/buffer \
pybindgen/examples/boost_shared_ptr \
pybindgen/examples/b \
pybindgen/examples/a \
pybindgen/benchmarks \
ns-3/utils \
ns-3/src/wimax/test \
ns-3/src/wimax/model \
ns-3/src/wimax/helper \
ns-3/src/wimax/examples \
ns-3/src/wifi/test \
ns-3/src/wifi/model \
ns-3/src/wifi/helper \
ns-3/src/wifi/examples \
ns-3/src/wave/test \
ns-3/src/wave/model \
ns-3/src/wave/helper \
ns-3/src/wave/examples \
ns-3/src/visualizer/model \
ns-3/src/virtual-net-device/model \
ns-3/src/virtual-net-device/examples \
ns-3/src/vanet/test \
ns-3/src/vanet/model \
ns-3/src/vanet/examples \
ns-3/src/uan/test \
ns-3/src/uan/model \
ns-3/src/uan/helper \
ns-3/src/uan/examples \
ns-3/src/topology-read/test \
ns-3/src/topology-read/model \
ns-3/src/topology-read/helper \
ns-3/src/topology-read/examples \
ns-3/src/test/perf \
ns-3/src/test/ns3wifi \
ns-3/src/test/ns3tcp \
ns-3/src/test \
ns-3/src/tap-bridge/model \
ns-3/src/tap-bridge/helper \
ns-3/src/tap-bridge/examples \
ns-3/src/stats/test \
ns-3/src/stats/model \
ns-3/src/stats/helper \
ns-3/src/stats/examples \
ns-3/src/spectrum/test \
ns-3/src/spectrum/model \
ns-3/src/spectrum/helper \
ns-3/src/spectrum/examples \
ns-3/src/sixlowpan/test \
ns-3/src/sixlowpan/model \
ns-3/src/sixlowpan/helper \
ns-3/src/sixlowpan/examples \
ns-3/src/propagation/test \
ns-3/src/propagation/model \
ns-3/src/propagation/examples \
ns-3/src/point-to-point-layout/model \
ns-3/src/point-to-point/test \
ns-3/src/point-to-point/model \
ns-3/src/point-to-point/helper \
ns-3/src/point-to-point/examples \
ns-3/src/openflow/test \
ns-3/src/openflow/model \
ns-3/src/openflow/helper \
ns-3/src/openflow/examples \
ns-3/src/olsr/test \
ns-3/src/olsr/model \
ns-3/src/olsr/helper \
ns-3/src/olsr/examples \
ns-3/src/nix-vector-routing/model \
ns-3/src/nix-vector-routing/helper \
ns-3/src/nix-vector-routing/examples \
ns-3/src/network/utils \
ns-3/src/network/test \
ns-3/src/network/model \
ns-3/src/network/helper \
ns-3/src/network/examples \
ns-3/src/netanim/test \
ns-3/src/netanim/model \
ns-3/src/netanim/examples \
ns-3/src/ndnSIM/utils/tracers \
ns-3/src/ndnSIM/utils \
ns-3/src/ndnSIM/tools \
ns-3/src/ndnSIM/test \
ns-3/src/ndnSIM/plugins/tracers-broken \
ns-3/src/ndnSIM/plugins/tracers-broken/tracers \
ns-3/src/ndnSIM/plugins/topology \
ns-3/src/ndnSIM/plugins/mobility \
ns-3/src/ndnSIM/plugins/ip-faces \
ns-3/src/ndnSIM/ndn.cxx \
ns-3/src/ndnSIM/model/wire \
ns-3/src/ndnSIM/model/wire/ndnsim \
ns-3/src/ndnSIM/model/wire/ccnb \
ns-3/src/ndnSIM/model/wire/ccnb/ccnb-parser/visitors \
ns-3/src/ndnSIM/model/wire/ccnb/ccnb-parser/syntax-tree \
ns-3/src/ndnSIM/model/pit \
ns-3/src/ndnSIM/model \
ns-3/src/ndnSIM/model/fw \
ns-3/src/ndnSIM/model/fib \
ns-3/src/ndnSIM/model/cs \
ns-3/src/ndnSIM/helper \
ns-3/src/ndnSIM/examples \
ns-3/src/ndnSIM/examples/custom-strategies \
ns-3/src/ndnSIM/examples/custom-apps \
ns-3/src/ndnSIM/apps \
ns-3/src/mpi/model \
ns-3/src/mpi/examples \
ns-3/src/mobility/test \
ns-3/src/mobility/model \
ns-3/src/mobility/helper \
ns-3/src/mobility/examples \
ns-3/src/mesh/test \
ns-3/src/mesh/test/flame \
ns-3/src/mesh/test/dot11s \
ns-3/src/mesh/model \
ns-3/src/mesh/model/flame \
ns-3/src/mesh/model/dot11s \
ns-3/src/mesh/helper \
ns-3/src/mesh/helper/flame \
ns-3/src/mesh/helper/dot11s \
ns-3/src/mesh/examples \
ns-3/src/lte/test \
ns-3/src/lte/model \
ns-3/src/lte/helper \
ns-3/src/lte/examples \
ns-3/src/lr-wpan/test \
ns-3/src/lr-wpan/model \
ns-3/src/lr-wpan/helper \
ns-3/src/lr-wpan/examples \
ns-3/src/internet/test \
ns-3/src/internet/model \
ns-3/src/internet/helper \
ns-3/src/internet/examples \
ns-3/src/flow-monitor/test \
ns-3/src/flow-monitor/model \
ns-3/src/flow-monitor/helper \
ns-3/src/fd-net-device/model \
ns-3/src/fd-net-device/helper \
ns-3/src/fd-net-device/examples \
ns-3/src/energy/test \
ns-3/src/energy/model \
ns-3/src/energy/helper \
ns-3/src/energy/examples \
ns-3/src/emu/model \
ns-3/src/emu/helper \
ns-3/src/emu/examples \
ns-3/src/dsr/test \
ns-3/src/dsr/model \
ns-3/src/dsr/helper \
ns-3/src/dsr/examples \
ns-3/src/dsdv/test \
ns-3/src/dsdv/model \
ns-3/src/dsdv/helper \
ns-3/src/dsdv/examples \
ns-3/src/csma-layout/model \
ns-3/src/csma-layout/examples \
ns-3/src/csma/model \
ns-3/src/csma/helper \
ns-3/src/csma/examples \
ns-3/src/core/test \
ns-3/src/core/model \
ns-3/src/core/helper \
ns-3/src/core/examples \
ns-3/src/core/bindings \
ns-3/src/config-store/model \
ns-3/src/config-store/examples \
ns-3/src/click/test \
ns-3/src/click/model \
ns-3/src/click/helper \
ns-3/src/click/examples \
ns-3/src/buildings/test \
ns-3/src/buildings/model \
ns-3/src/buildings/helper \
ns-3/src/buildings/examples \
ns-3/src/brite/test \
ns-3/src/brite/helper \
ns-3/src/brite/examples \
ns-3/src/bridge/model \
ns-3/src/bridge/helper \
ns-3/src/bridge/examples \
ns-3/src/bittorrent/model/tracker \
ns-3/src/bittorrent/model/common \
ns-3/src/bittorrent/model/common/3rd-party \
ns-3/src/bittorrent/model/client/strategies \
ns-3/src/bittorrent/model/client \
ns-3/src/bittorrent/helper/no-tap \
ns-3/src/bittorrent/helper \
ns-3/src/bittorrent/examples \
ns-3/src/applications/test \
ns-3/src/applications/model \
ns-3/src/applications/helper \
ns-3/src/aodv/test \
ns-3/src/aodv/model \
ns-3/src/aodv/helper \
ns-3/src/aodv/examples \
ns-3/src/antenna/test \
ns-3/src/antenna/model \
ns-3/scratch \
ns-3/ip \
ns-3/examples/wireless \
ns-3/examples/udp-client-server \
ns-3/examples/udp \
ns-3/examples/tutorial \
ns-3/examples/tcp \
ns-3/examples/stats \
ns-3/examples/socket \
ns-3/examples/routing \
ns-3/examples/realtime \
ns-3/examples/naming \
ns-3/examples/matrix-topology \
ns-3/examples/ipv6 \
ns-3/examples/error-model \
ns-3/examples/energy \
ns-3/cartoo \
ns-3/build/utils \
ns-3/build/src/wimax/model \
ns-3/build/src/wimax/helper \
ns-3/build/src/wimax/examples \
ns-3/build/src/wimax/bindings \
ns-3/build/src/wifi/model \
ns-3/build/src/wifi/helper \
ns-3/build/src/wifi/examples \
ns-3/build/src/wifi/bindings \
ns-3/build/src/wave/model \
ns-3/build/src/wave/helper \
ns-3/build/src/wave/examples \
ns-3/build/src/wave/bindings \
ns-3/build/src/visualizer/model \
ns-3/build/src/visualizer/bindings \
ns-3/build/src/virtual-net-device/model \
ns-3/build/src/virtual-net-device/examples \
ns-3/build/src/virtual-net-device/bindings \
ns-3/build/src/vanet/model \
ns-3/build/src/vanet/examples \
ns-3/build/src/uan/model \
ns-3/build/src/uan/helper \
ns-3/build/src/uan/examples \
ns-3/build/src/uan/bindings \
ns-3/build/src/topology-read/model \
ns-3/build/src/topology-read/helper \
ns-3/build/src/topology-read/examples \
ns-3/build/src/topology-read/bindings \
ns-3/build/src/tap-bridge/model \
ns-3/build/src/tap-bridge/helper \
ns-3/build/src/tap-bridge/examples \
ns-3/build/src/tap-bridge/bindings \
ns-3/build/src/stats/model \
ns-3/build/src/stats/helper \
ns-3/build/src/stats/examples \
ns-3/build/src/stats/bindings \
ns-3/build/src/spectrum/model \
ns-3/build/src/spectrum/helper \
ns-3/build/src/spectrum/examples \
ns-3/build/src/spectrum/bindings \
ns-3/build/src/sixlowpan/model \
ns-3/build/src/sixlowpan/helper \
ns-3/build/src/sixlowpan/examples \
ns-3/build/src/sixlowpan/bindings \
ns-3/build/src/propagation/model \
ns-3/build/src/propagation/examples \
ns-3/build/src/propagation/bindings \
ns-3/build/src/point-to-point-layout/model \
ns-3/build/src/point-to-point-layout/bindings \
ns-3/build/src/point-to-point/model \
ns-3/build/src/point-to-point/helper \
ns-3/build/src/point-to-point/examples \
ns-3/build/src/point-to-point/bindings \
ns-3/build/src/olsr/model \
ns-3/build/src/olsr/helper \
ns-3/build/src/olsr/examples \
ns-3/build/src/olsr/bindings \
ns-3/build/src/nix-vector-routing/model \
ns-3/build/src/nix-vector-routing/helper \
ns-3/build/src/nix-vector-routing/examples \
ns-3/build/src/nix-vector-routing/bindings \
ns-3/build/src/network/utils \
ns-3/build/src/network/model \
ns-3/build/src/network/helper \
ns-3/build/src/network/examples \
ns-3/build/src/network/bindings \
ns-3/build/src/netanim/model \
ns-3/build/src/netanim/examples \
ns-3/build/src/ndnSIM/utils/tracers \
ns-3/build/src/ndnSIM/utils \
ns-3/build/src/ndnSIM/tools \
ns-3/build/src/ndnSIM/plugins/topology \
ns-3/build/src/ndnSIM/plugins/ip-faces \
ns-3/build/src/ndnSIM/ndn.cxx \
ns-3/build/src/ndnSIM/model/wire \
ns-3/build/src/ndnSIM/model/wire/ndnsim \
ns-3/build/src/ndnSIM/model/wire/ccnb \
ns-3/build/src/ndnSIM/model/wire/ccnb/ccnb-parser/visitors \
ns-3/build/src/ndnSIM/model/wire/ccnb/ccnb-parser/syntax-tree \
ns-3/build/src/ndnSIM/model/pit \
ns-3/build/src/ndnSIM/model \
ns-3/build/src/ndnSIM/model/fw \
ns-3/build/src/ndnSIM/model/fib \
ns-3/build/src/ndnSIM/model/cs \
ns-3/build/src/ndnSIM/helper \
ns-3/build/src/ndnSIM/examples \
ns-3/build/src/ndnSIM/examples/custom-strategies \
ns-3/build/src/ndnSIM/examples/custom-apps \
ns-3/build/src/ndnSIM/bindings \
ns-3/build/src/ndnSIM/apps \
ns-3/build/src/mpi/model \
ns-3/build/src/mpi/examples \
ns-3/build/src/mpi/bindings \
ns-3/build/src/mobility/model \
ns-3/build/src/mobility/helper \
ns-3/build/src/mobility/examples \
ns-3/build/src/mobility/bindings \
ns-3/build/src/mesh/model \
ns-3/build/src/mesh/model/flame \
ns-3/build/src/mesh/model/dot11s \
ns-3/build/src/mesh/helper \
ns-3/build/src/mesh/helper/flame \
ns-3/build/src/mesh/helper/dot11s \
ns-3/build/src/mesh/examples \
ns-3/build/src/mesh/bindings \
ns-3/build/src/lte/model \
ns-3/build/src/lte/helper \
ns-3/build/src/lte/examples \
ns-3/build/src/lte/bindings \
ns-3/build/src/lr-wpan/model \
ns-3/build/src/lr-wpan/helper \
ns-3/build/src/lr-wpan/examples \
ns-3/build/src/lr-wpan/bindings \
ns-3/build/src/internet/model \
ns-3/build/src/internet/helper \
ns-3/build/src/internet/examples \
ns-3/build/src/internet/bindings \
ns-3/build/src/flow-monitor/model \
ns-3/build/src/flow-monitor/helper \
ns-3/build/src/flow-monitor/bindings \
ns-3/build/src/fd-net-device/model \
ns-3/build/src/fd-net-device/helper \
ns-3/build/src/fd-net-device/examples \
ns-3/build/src/fd-net-device/bindings \
ns-3/build/src/energy/model \
ns-3/build/src/energy/helper \
ns-3/build/src/energy/examples \
ns-3/build/src/energy/bindings \
ns-3/build/src/emu/model \
ns-3/build/src/emu/helper \
ns-3/build/src/emu/examples \
ns-3/build/src/emu/bindings \
ns-3/build/src/dsr/model \
ns-3/build/src/dsr/helper \
ns-3/build/src/dsr/examples \
ns-3/build/src/dsr/bindings \
ns-3/build/src/dsdv/model \
ns-3/build/src/dsdv/helper \
ns-3/build/src/dsdv/examples \
ns-3/build/src/dsdv/bindings \
ns-3/build/src/csma-layout/model \
ns-3/build/src/csma-layout/examples \
ns-3/build/src/csma-layout/bindings \
ns-3/build/src/csma/model \
ns-3/build/src/csma/helper \
ns-3/build/src/csma/examples \
ns-3/build/src/csma/bindings \
ns-3/build/src/core/model \
ns-3/build/src/core/helper \
ns-3/build/src/core/examples \
ns-3/build/src/core/bindings \
ns-3/build/src/config-store/model \
ns-3/build/src/config-store/examples \
ns-3/build/src/config-store/bindings \
ns-3/build/src/buildings/model \
ns-3/build/src/buildings/helper \
ns-3/build/src/buildings/examples \
ns-3/build/src/buildings/bindings \
ns-3/build/src/bridge/model \
ns-3/build/src/bridge/helper \
ns-3/build/src/bridge/examples \
ns-3/build/src/bridge/bindings \
ns-3/build/src/bittorrent/model/tracker \
ns-3/build/src/bittorrent/model/common \
ns-3/build/src/bittorrent/model/common/3rd-party \
ns-3/build/src/bittorrent/model/client/strategies \
ns-3/build/src/bittorrent/model/client \
ns-3/build/src/bittorrent/helper \
ns-3/build/src/bittorrent/examples \
ns-3/build/src/applications/model \
ns-3/build/src/applications/helper \
ns-3/build/src/applications/bindings \
ns-3/build/src/aodv/model \
ns-3/build/src/aodv/helper \
ns-3/build/src/aodv/examples \
ns-3/build/src/aodv/bindings \
ns-3/build/src/antenna/model \
ns-3/build/src/antenna/bindings \
ns-3/build/scratch/subdir \
ns-3/build/scratch \
ns-3/build/examples/wireless \
ns-3/build/examples/udp-client-server \
ns-3/build/examples/udp \
ns-3/build/examples/tutorial \
ns-3/build/examples/tcp \
ns-3/build/examples/stats \
ns-3/build/examples/socket \
ns-3/build/examples/routing \
ns-3/build/examples/realtime \
ns-3/build/examples/naming \
ns-3/build/examples/matrix-topology \
ns-3/build/examples/ipv6 \
ns-3/build/examples/error-model \
ns-3/build/examples/energy \
ns-3/build/.conf_check_fe0ca542f39064c5a14ee41a2e983996/testbuild \
ns-3/build/.conf_check_fe0ca542f39064c5a14ee41a2e983996 \
ns-3/build/.conf_check_fa0c4ec9c63ac505501cc0863d9bdc48/testbuild \
ns-3/build/.conf_check_fa0c4ec9c63ac505501cc0863d9bdc48 \
ns-3/build/.conf_check_f00bb2460dc7019f64c1a347be5879fa/testbuild \
ns-3/build/.conf_check_f00bb2460dc7019f64c1a347be5879fa \
ns-3/build/.conf_check_efd20fc635aad783e4d3953701740533 \
ns-3/build/.conf_check_ebd591dbc3bb45aa25214505e9aa0d0f/testbuild \
ns-3/build/.conf_check_ebd591dbc3bb45aa25214505e9aa0d0f \
ns-3/build/.conf_check_d8a2c40aecfb7c8eac7dd03fcbfb1110/testbuild \
ns-3/build/.conf_check_d8a2c40aecfb7c8eac7dd03fcbfb1110 \
ns-3/build/.conf_check_c94d96928742c001335a0559791a93d8/testbuild \
ns-3/build/.conf_check_c94d96928742c001335a0559791a93d8 \
ns-3/build/.conf_check_ace1886511f08627ee2e4ca020806295 \
ns-3/build/.conf_check_ab7199aa46fcaa2e15071e73776f8218/testbuild \
ns-3/build/.conf_check_ab7199aa46fcaa2e15071e73776f8218 \
ns-3/build/.conf_check_97f735b5464546b54ea13ec62d1c17e5/testbuild \
ns-3/build/.conf_check_97f735b5464546b54ea13ec62d1c17e5 \
ns-3/build/.conf_check_968fbcee789046a8c143bb4a6e302895/testbuild \
ns-3/build/.conf_check_968fbcee789046a8c143bb4a6e302895 \
ns-3/build/.conf_check_8dd79274749d59bf459dfbeb1200c7d7/testbuild \
ns-3/build/.conf_check_8dd79274749d59bf459dfbeb1200c7d7 \
ns-3/build/.conf_check_8d38681417ac64f5b5b7d4ca87b0e4f3/testbuild \
ns-3/build/.conf_check_8d38681417ac64f5b5b7d4ca87b0e4f3 \
ns-3/build/.conf_check_7c67b81911f8bf0aede92c843d0e47cf/testbuild \
ns-3/build/.conf_check_7c67b81911f8bf0aede92c843d0e47cf \
ns-3/build/.conf_check_79f849e1774b3cde8897857e178c7c8c/testbuild \
ns-3/build/.conf_check_79f849e1774b3cde8897857e178c7c8c \
ns-3/build/.conf_check_6c6255d84543ffa2d8b83c989561eef9/testbuild \
ns-3/build/.conf_check_6c6255d84543ffa2d8b83c989561eef9 \
ns-3/build/.conf_check_656b178ce7442053dff90315b31a1cc5 \
ns-3/build/.conf_check_61ecbfef21667d45a28decabe37fdf64 \
ns-3/build/.conf_check_5ef57bc0d8aa3565949b6ce1186fd4a7/testbuild \
ns-3/build/.conf_check_5ef57bc0d8aa3565949b6ce1186fd4a7 \
ns-3/build/.conf_check_48955ac54d2136a572805353a7b9b62d/testbuild \
ns-3/build/.conf_check_48955ac54d2136a572805353a7b9b62d \
ns-3/build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e/testbuild \
ns-3/build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e \
ns-3/build/.conf_check_3a82ef2f96ebcc67f6086c98d2e6291e/testbuild \
ns-3/build/.conf_check_3a82ef2f96ebcc67f6086c98d2e6291e \
ns-3/build/.conf_check_355be13189b7b0ddfb123175e2bb33a5/testbuild \
ns-3/build/.conf_check_355be13189b7b0ddfb123175e2bb33a5 \
ns-3/build/.conf_check_2be466e82e703a744ee152afe2b58299/testbuild \
ns-3/build/.conf_check_2be466e82e703a744ee152afe2b58299 \
ns-3/build/.conf_check_1f933b02106127ce3a9f4633a0e368e7/testbuild \
ns-3/build/.conf_check_1f933b02106127ce3a9f4633a0e368e7 \
ns-3/bindings/python \

