## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('bittorrent-no-story', ['bittorrent', 'wifi'])
    obj.source = 'bittorrent-no-story.cc'
    
    obj = bld.create_ns3_program('vodsim', ['bittorrent'])
    
    if bld.env['ENABLE_REAL_TIME']:
        obj.source = 'vodsim.cc'
    else:
        obj.source = 'vodsim-no-realtime.cc'
    
